security
Alex-javac/FinnhubAPI pull request #3
Opened 2021-09-23 16:24 UTC by Alex-javac

2021-09-27 07:47 UTC, AlRezz approved these changes
Внимательно читаем описание задания. Первым словом написано "Серсвис"
Мы не возвращаем страницы - у нас API и мы возвращаем результвты

2021-09-28 10:21 UTC, Poviraevsergei requested changes
Поправить недочёты что указаны. Посмотреть как правильно сделать регистрацию и авторизацию с помощью Spring Security. Переделать код чтобы можно было проверить процесс регистрации и доступ к разным эндпоинтам в зависимости от Роли(ADMIN, USER) через Postman.

2021-09-28 10:21 UTC, Poviraevsergei commented on src/main/java/com/itechart/finnhubapi/controller/AuthController.java
> +        return "login";
мы не работаем со страницами, возвращаем только данные.

2021-09-28 10:21 UTC, Poviraevsergei commented on src/main/java/com/itechart/finnhubapi/model/UserEntity.java
>  import javax.persistence.*;
мы должны видеть что импортируем, убрать *

2021-09-30 19:10 UTC, closed without merging